title: The Array Cast
description: A podcast about the array programming languages. Discussing APL, J, K, Q, BQN, and other array languages.
author: Conor Hoekstra &amp; Adám Brudzewsky
email: contact@arraycast.com
lang: en
copyright: "&#x2117; &amp; &#xA9; 2021–2026 The Array Cast"
logo: /assets/img/logo.webp
url: "https://www.arraycast.com"
# For temporary deployment at codereport.github.io/arraycast/, use:
# baseurl: "/arraycast"
# For final deployment at www.arraycast.com, use:
baseurl: ""

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
