title: The Array Cast
description: A podcast that explores the world of array programming languages including APL, J, BQN, K, Q, Uiua and more!
author: Conor Hoekstra &amp; Adám Brudzewsky
email: contact@arraycast.com
github_repo: https://github.com/codereport/arraycast
lang: en
copyright: "&#x2117; &amp; &#xA9; 2021–2026 The Array Cast"
logo: /assets/img/logo.webp
# For deployment at www.arraycast.com:
url: "https://www.arraycast.com"
baseurl: ""

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules
  - README.md
  - LICENSE
