title: The Array Cast
description: A podcast about the array programming languages. Discussing APL, J, K, Q, BQN, and other array languages.
author: Conor Hoekstra &amp; Adám Brudzewsky
email: contact@arraycast.com
lang: en
copyright: "&#x2117; &amp; &#xA9; 2021–2026 The Array Cast"
logo: /assets/img/logo.webp
url: "https://www.arraycast.com"
# baseurl: "/" # the subpath of your site, e.g. /blog

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
